# .github/workflows/deploy.yml

name: Deploy Static Website

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Important: Grant write permissions for the GITHUB_TOKEN

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Add your actual build steps here (uncomment and adjust as needed):
      # - name: Setup Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '20'
      # - name: Install dependencies
      #   run: npm install
      # - name: Build static website
      #   run: npm run build # Replace with your actual build command, e.g., 'hugo', 'jekyll build', 'npx astro build'

      # IMPORTANT: Ensure your build output is in a known directory.
      # For GitHub Pages, this is often 'public', 'build', or '_site'.
      # Let's assume your build command outputs to 'public'.

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 # Use this action for deploying to gh-pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # This token is automatically provided by GitHub
          publish_dir: ./public # This should be the directory where your built website files are located
          publish_branch: gh-pages # Uncomment if you're deploying to a 'gh-pages' branch
                                     # If you configured GitHub Pages to deploy from 'main' and root, you might not need this.
